#--------------------------------------------------------------------------------------
#
#  Copyright: (c) 2020 Bentley Systems, Incorporated. All rights reserved. 
#
#--------------------------------------------------------------------------------------

# DO NOT EDIT!
# This file is automatically generated during the build process

API_VERSION = "24.0.0"
